export const INSERT_COMMENT_SAGA = "INSERT_COMMENT_SAGA";
export const UPDATE_COMMENT_SAGA = "UPDATE_COMMENT_SAGA";
export const DELETE_COMMENT_SAGA = "DELETE_COMMENT_SAGA";
export const GET_ALL_COMMENT = "GET_ALL_COMMENT";
export const GET_ALL_COMMENT_SAGA = "GET_ALL_COMMENT_SAGA";
